### ISSUE TITLE
Missing Mob - Level 2 Veteran Clan Bills - Rhino Beetle

### ISSUE THREAD

**Issue by DrWolffan** [Kataera/DailyHuntAssistMode#1]
The mob Rhino Beetle from StB is unable to be read from the Level 2 Veteran Clan Bills.

**Comment by DrWolffan** [comment]
![image](https://github.com/user-attachments/assets/92a2db15-92d1-4699-b939-50250931e651)

Killed the mob on my own, but figured I'd add a picture

**Comment by Kataera** [comment]
Not 100% sure I've fixed this as I was unable to reproduce the issue. Please give it a go!

**Comment by DrWolffan** [comment]
![image](https://github.com/user-attachments/assets/e1db36ef-a7d7-468b-9d94-432a7fa3b2da)
Still an error here

**Comment by DrWolffan** [comment]
![image](https://github.com/user-attachments/assets/8c703364-f90e-4eb1-b8e0-c747ef970d10)
Still an error here

**Comment by DrWolffan** [comment]
![image](https://github.com/user-attachments/assets/8b071673-ddb3-4965-ae44-911e31030365)
Still an error here (Had wrong pic)

**Comment by Kataera** [comment]
I've found what the issue is, there's a mob with the same name in Dawntrail and the original code isn't setup for dealing with duplicates.

I'll fix this later today.

**Comment by Kataera** [comment]
Should be fixed now, please give it a go and let me know!
